import { Icon } from '@iconify-icon/react'
import { Button, Chip } from '@nextui-org/react'
import { audioEvents } from '~/api/audioEvents'
import { analyzeTracks } from '~/api/audioHandlers'
import { appState, setAppState } from '~/api/db/appState'
import { Track, addToMix, getPrefs, useLiveQuery } from '~/api/db/dbHandlers'
